### ISSUE TITLE
Type definition file for TypeScript is missing

### ISSUE THREAD

**Issue by Chris2011** [P3trur0/vue-country-flag#13]
When I use TypeScript and import this lib, I got the error inside of VSCode and via serve, that the typedef file is missing. If it is easy for you, please add it. Otherwise, I will have a look later to generate one, when I have time.

**Comment by P3trur0** [comment]
Chris, thanks for mentioning that. I'll add the typedef as soon as I find few spare time :relaxed:

**Comment by Chris2011** [comment]
Grest, thx :)

**Comment by P3trur0** [comment]
@Chris2011 version 1.3.0 contains also the `.d.ts` files, so you can use the component also in TypeScript files.
Thanks for spotting the issue. 😄

**Comment by Chris2011** [comment]
Works w/o errors. Thx :)
