### ISSUE TITLE
Space still available after scaling

### ISSUE THREAD

**Issue by Chris2011** [P3trur0/vue-country-flag#14]
As you can see it here in my image:

![image](https://user-images.githubusercontent.com/795658/63354825-6d0a1000-c365-11e9-8fcb-b45032c9baa9.png)

I use the medium flag. The problem is, that the space around is to high. It comes from the width/height 64px whily you scale it down to half of it. So it will show 32px but it will keep the original height/width. Just scaled down.

When I override the 64px with e.g. 32px (due to medium that I want) the position of the css-sprite is not correct anymore. See:

![image](https://user-images.githubusercontent.com/795658/63355070-db4ed280-c365-11e9-9e08-b76f969f229f.png)

So I can try to fix the CSS for my needs (could be tricky) or it should be an option to shrink it really down to the exact size. Or you should have different css-sprites for small, medium, large (?).

**Comment by Chris2011** [comment]
So my case is, I need a differenz size (medium) but it should fit in the box w/o having the original size.

**Comment by P3trur0** [comment]
Hi Chris, currently the component comes with a single sprite and simple CSS math for scaling it according to the flag size. 
Tomorrow I have free time and I'll spend it in figuring out this issue.
Obviously, if you have any idea, please come with either suggestions or a PR ☺️

**Comment by P3trur0** [comment]
@Chris2011 please check it out version 1.3.0 of the component. It fixes this issue by adapting also the vertical margins according to the selected size of the flag.
Thanks for spotting this.

**Comment by Chris2011** [comment]
Working perfect. Thx :)
