### ISSUE TITLE
Incorrect component tag in docs

### ISSUE THREAD

**Issue by mindaugasvcs** [P3trur0/vue-country-flag#17]

**Comment by P3trur0** [comment]
Hi @mindaugasvcs thank you for spotting the issue. Could you please mention the line you're referring to?
Thanks!

**Comment by mindaugasvcs** [comment]
How to use
Register CountryFlag component in your app. You can use two approaches:

in main.js you can mount it as a global Vue component:
import Vue from 'vue'
import CountryFlag from 'vue-country-flag'

Vue.component('**vue-country-flag**', CountryFlag)
Should be country-flag, no big deal but stil I could not manage to use this in a global install context.

**Comment by P3trur0** [comment]
Thanks for highlighting that! Documentation fixed.
