### ISSUE TITLE
Missing Flag

### ISSUE THREAD

**Issue by BobanStanojevicST** [P3trur0/vue-country-flag#20]
Flag for Kosovo is currently missing

**Comment by P3trur0** [comment]
Hi @BobanStanojevicST thanks for pointing that! In these weeks I have not enough free time to spend on the issue.
I hope to have more time in October, apologize for this 😢

**Comment by MatthewAry** [comment]
Other missing flags

- Ascension Island
- Caribbean Netherlands
- Cocos (Keeling) Islands
- Christmas Island
- French Guiana
- Guadeloupe
- British Indian Ocean Territory
- St. Pierre & Miquelon
- Réunion
- Svalbard & Jan Mayen
- Sint Maarten
- Tristan da Cunha
- Kosovo

I'm creating a system that essentially reproduces the phone number field design used in Google Contacts. I'm getting Country Data from com.google.i18n.phonenumbers supported regions list. BTW the country list from google's phone number library is more comprehensive than the list shown on Google's contacts web app.

**Comment by P3trur0** [comment]
Thanks for adding more details to this issue! By the end of this month I'd be able to fix this!

**Comment by P3trur0** [comment]
@BobanStanojevicST @MatthewAry all the missing flags you mentioned have been added in **2.0.0**. Thanks for reporting that.
