### ISSUE TITLE
missing flags css after fresh install

### ISSUE THREAD

**Issue by luckylooke** [P3trur0/vue-country-flag#23]
Hello!
Thank you for sharing package
but after installation by 
```
npm i vue-country-flag
+ vue-country-flag@1.3.1
added 1 package from 1 contributor and audited 939528 packages in 26.977s
```
I am getting error:
```
This relative module was not found:
* ./css/flags/flags.min.css in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-country-flag/src/CountryFlag.vue?vue&type=script&lang=js&
```
And I have double-checked there is no such folder as css in src in node_modules, I can see it here on github.. but probably problem is in package.json:
```
"files": [
    "dist/*",
    "src/**/*.vue"
  ],
```
as you can see css is not included

I have used:
npm -v
6.13.4
for installation

I have tried yarn 1.15.2 .. but same result

Thanks :)

**Comment by P3trur0** [comment]
Hi @luckylooke thank you for appreciating this package and pointing out this error! I'll try to fix ASAP.
Alternatively, please feel free to fix it and open a PR :)

**Comment by luckylooke** [comment]
I have changed my configuration and the problem disappeared, probably it uses now just code from /dist where those flags are inlined in bundle, so for me it is no more issue, but I am not sure what convenience is here. Whether src folder should be in package files or not.. if so, then corresponding css dependency is missing, if not, maybe you should remove "src/**/*.vue" from package. 

:)

**Comment by P3trur0** [comment]
@luckylooke thanks! I'll give it a look 😸

**Comment by P3trur0** [comment]
@luckylooke sorry for being late. I've taken your suggestion of getting rid of `.vue` file in the final npm bundle. Thank you :)
