### ISSUE TITLE
Flags invisible for Android chrome browser

### ISSUE THREAD

**Issue by Ruchirr** [P3trur0/vue-country-flag#26]
Tried both alpha 2 and alpha 3 ISSO 3166-1 it gives error. Secondly the flags are bit blurry for Firefox. Please let me know what are the supporting changes to be importantly for chrome android app. Thanks in advance.

**Comment by P3trur0** [comment]
Hi, thanks for trying this package! :smile_cat: 
Which error do you get? Could you please be more specific?
Also, what do you mean with supporting changes for Chrome Android app? By installing it as Vue component it should properly work within Chrome.

**Comment by Ruchirr** [comment]
Hi, thanks for a quick response and for creating this beautiful plugin. I am using Nuxt.js and the flags do appear in chrome browsers for Mac and Windows. 

The only issue is when I open the web app on my Android phone's chrome app, flags disappears (The chrome app is updated to the latest version). However, the plugin works fine on Firefox.

Furthermore, it works well on all browser apps in iPhone.

Therefore, what could be the issue. Could you please help me with this.

**Comment by P3trur0** [comment]
Hi @Ruchirr thanks for using it.

A possible problem might be that vue-country-flag uses a sprite Base64 encoded in the CSS itself. I am not familiar of the current behavior of Chrome, but currently that's the first idea coming to my mind.

However, I will investigate about the issue.

**Comment by Ruchirr** [comment]
Hi @P3trur0 most welcome.

Alright, I will check that out. I tried loading .svg files in <img /> with a loop. They work well with all the browsers, just a head up to save time for debugging. 

Sure thing.

**Comment by P3trur0** [comment]
Hi @Ruchirr, so far I am not able to replicate the issue. Do you have some snippet to share in order to help me in replicate it?

Thanks!

**Comment by Ruchirr** [comment]
Hi @P3trur0, 

Yes I have one screen shot for the issue, The screen shot provides the application running state on Android Chrome App: 

https://user-images.githubusercontent.com/30252229/80860331-4baa4380-8caa-11ea-9730-79e91e2e5eb5.png

Secondly, the code if you want to take a look..

https://github.com/Ruchirr/covid-and-news/blob/deploy-india-corona-data/components/cards.vue

Hope this helps.

**Comment by P3trur0** [comment]
Hi @Ruchirr,

I am trying to reproduce the problem and indeed, on an Android emulator, I don't see the flags of your application.
Alas, by doing a simple test with another small Vue application, I see the flags properly. Maybe you should investigate in your source code too, since by launching it on my machine I stumbled upon a series of Vue warnings in the DevTools console.

Please, keep me updated about that, so I will further investigate on it.

![test](https://user-images.githubusercontent.com/11474157/80908435-12acb600-8d20-11ea-963e-d4cb251b3d61.png)

**Comment by kokhlo** [comment]
Hello everyone,

I have a same issue not only in Android Chrome browser, but as well in case of building my project as Apache Cordova mobile application. All flags I used in are invisible. Could you help me, please with it?

**Comment by P3trur0** [comment]
Hello @kokhlo thanks for mentioning this. I am not very familiar with Apache Cordova, so I cannot repeat your scenario easily in order to troubleshot this. Could please help me in setting up a testing scenario to try to address the issue?

**Comment by kokhlo** [comment]
@P3trur0, yes, thanks for your answer. I'll create a repository with testing environment for this purpose later and share link with your with some other details. This issue is quite important for me at the moment.

**Comment by P3trur0** [comment]
@kokhlo yes please :) I'll be glad to help in fixing it.

**Comment by kokhlo** [comment]
Hello @P3trur0,

repository has been created: https://github.com/kokhlo/VueFlagsTestRepo.git
Now you can fork it and get an example of Vue project and android application in one. Ping me if you need clarification or something else. Thanks in advance! :)

**Comment by P3trur0** [comment]
@kokhlo thank you! I'll give it a look tonight. Do you see the error even on emulator, right? Indeed I have not a physical android device to test it directly.

**Comment by kokhlo** [comment]
I see this issue permanently , as on the physical device as in emulator.

**Comment by P3trur0** [comment]
Do you see the issue also while launching the test app with `quasar dev` and browsing it through a desktop Chrome browser?

So far I was able to try both `quasar dev` and `quasar build` and I see the flags.

I still need more time to try it on Android emulators.

**Comment by P3trur0** [comment]
@kokhlo I was able to reproduce the problem, now thanks to your useful sample project I'll be able to investigate it further. I'll keep you updated about my findings.

**Comment by P3trur0** [comment]
@kokhlo which Android version are you using? In my emulator **Pixel_3a_API_30** the flags appear.

**Comment by kokhlo** [comment]
Oh Gosh, @P3trur0, thanks for your help. I'll try it a bit later but I'm confident it should work!

I will definitely write later about the results.

**Comment by alfienguyen** [comment]
@P3trur0  @kokhlo  Do you have any update re. this issue? I’m facing the same problem with my app (using Vuetify framework FYI)

**Comment by P3trur0** [comment]
@alfienguyen I was trying to understand why the bundled version of the component did not work on Android, but so far my investigations stopped at the Base64 encoded image in the .js.  

It seems that Android view does not render it properly. At the end of this week I might release a component version with a bundle generated from a later version of the Rollup plugin I am using for bundling the component, but I am not sure it will fix this issue as well.

**Comment by alfienguyen** [comment]
@P3trur0  FYI this library works fine on Android browser https://github.com/Yummygum/vue-flagpack 
Hope this gives you some clues to fix the issue

**Comment by P3trur0** [comment]
Thanks @alfienguyen I had a look at that component as well. It seems is using another component as a dependency, where the flags are rendered via SVG files. 
`vue-country-flag` instead is a zero dependency component, that bundles the flags as PNG image base64 encoded. It seems that the issue is because of some problems in rendering this encoded image.

**Comment by florian-lefebvre** [comment]
Hi, I also encounter this issue (https://special-characters-frontend.vercel.app/) @P3trur0.

**Comment by P3trur0** [comment]
Hello, thanks for reporting this.
Latest v.2.1.0 fixes the issue. Please, let me know if you face any other problem in using the component on Android.

**Comment by florian-lefebvre** [comment]
Hi @P3trur0 it still seems broken. It looks like it keeps the width and height of the flag (before there was just nothing) but it's still not showing.

You can see it at the top right:
![image](https://user-images.githubusercontent.com/69633530/118445040-37d35300-b6ee-11eb-8e78-21fb6cc1f006.png)

**Comment by P3trur0** [comment]
Hi @florian-lefebvre do you have any snippet that could I use to reproduce the issue?

**Comment by florian-lefebvre** [comment]
package.json
```json
{
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build --modern",
    "start": "nuxt start",
  },
  "dependencies": {
    "core-js": "^3.10.1",
    "nuxt": "^2.15.4",
    "vue-country-flag": "^2.1.1"
  },
  "devDependencies": {}
}
```
nuxt.config.js
```js
export default {
    plugins: [
      "~/plugins/vue-country-flag.js",
    ],
    components: true,
}
```
plugins/vue-country-flag.js
```js
import Vue from "vue";
import CountryFlag from "vue-country-flag";

Vue.component("country-flag", CountryFlag);
```
pages/index.vue
```vue
<template>
    <country-flag country="fr" rounded />
</template>
```
I think it should be enough @P3trur0

**Comment by P3trur0** [comment]
sure, I'll give a shot during this weekend. Thanks for reporting this.

**Comment by P3trur0** [comment]
Hello @florian-lefebvre, I am trying to reproduce the issue, but with no luck so far.
I built a local Nuxt app launched as:

`npm run build && npm run start`

![immagine](https://user-images.githubusercontent.com/11474157/119383275-6a1f1a80-bcc3-11eb-847e-7010890d4ecf.png)

It renders flag properly both on desktop and mobile Brave (or any Chromium based) browser on Android. Like this:

![immagine](https://user-images.githubusercontent.com/11474157/119383603-d3069280-bcc3-11eb-821b-f4d4afe49b6b.png)

Moreover, browsing through your special-characters website (btw, nice!) I see the proper background flags file, I mean
[https://special-characters.vercel.app/_nuxt/img/flags.b698908.png](
https://special-characters.vercel.app/_nuxt/img/flags.b698908.png). So at CSS it seems all properly set up.

Do you have any way to check if your developer tools notifies any warning or error, please?
Also, is your local production build showing the flag as expected?

**Comment by florian-lefebvre** [comment]
Hi! I just tried in Brave and Duckduckgo on my Samsung Galaxy A10 and flags don't show so I guess it's related with my phone model... I don't know how I can use dev tools on mobile.

**Comment by florian-lefebvre** [comment]
I just saw [that](https://stackoverflow.com/questions/37256331/is-it-possible-to-open-developer-tools-console-in-chrome-on-android-phone), I gonna try it.

**Comment by P3trur0** [comment]
Actually even on my Xiaomi I see the problem browsing to your website, instead the Nuxt app I built from scratch following your skeleton example works without problems...

About remote debugging, please, check this out:

https://developer.chrome.com/docs/devtools/remote-debugging

**Comment by florian-lefebvre** [comment]
That's an awesome tool ! I get
![image](https://user-images.githubusercontent.com/69633530/119385598-9e480a80-bcc6-11eb-97fc-0663e9cb339b.png)

**Comment by florian-lefebvre** [comment]
Never mind the same happens on pc

**Comment by P3trur0** [comment]
Yup, it could be the issue. It seems that your hosting is not getting the proper URL for the flags. It seems strange though, since I see the CSS referring to the following:

https://special-characters.vercel.app/_nuxt/img/flags.b698908.png and it does exist.

Maybe, as a possible workaround, you could manually upload the flags file in the expected location (i.e.: your dist folder).

**Comment by P3trur0** [comment]
Hello @florian-lefebvre, I've just created an example here:

https://nuxtjs-p3trur0.vercel.app/

And I see the image both on desktop and Android.

You can find the example here: 

https://github.com/P3trur0/nuxtjs-demo

**Comment by florian-lefebvre** [comment]
Thx! It also works for me, I'll check your repo to see what I'm doing wrong

**Comment by florian-lefebvre** [comment]
Actually there is a huge difference between your repo and mine: I'm using SSR and you're not (`mode: spa` in nuxt.config.js).

**Comment by florian-lefebvre** [comment]
I don't how you have setup your project but you need to add https://github.com/nuxt/vercel-builder by adding a `vercel.json` file:
```json
{
  "version": 2,
  "builds": [
    {
      "src": "nuxt.config.js",
      "use": "@nuxtjs/vercel-builder"
    }
  ]
}
```

**Comment by P3trur0** [comment]
When you write:

> I don't know how you have setup your project on vercel @P3trur0 but you need to use [nuxt/vercel-builder](https://github.com/nuxt/vercel-builder) by adding a `vercel.json` file:
> 
> ```json
> {
>   "version": 2,
>   "builds": [
>     {
>       "src": "nuxt.config.js",
>       "use": "@nuxtjs/vercel-builder"
>     }
>   ]
> }
> ```

Do you think that this may be the possible cause of the issue? I simply deployed a demo application and independently of this script all the expected resources of my dist folder have been properly updated and pushed on Vercel hosting.

---

Also, about your statement here:

> Actually there is a huge difference between your repo and mine: I'm using SSR and you're not (`mode: spa` in nuxt.config.js).

so far I had no chance to see your actual code, so I am just trying a small example built as you mentioned [here](https://github.com/P3trur0/vue-country-flag/issues/26#issuecomment-844067669), where I didn't see any mention to the SSR execution of your code. Alas, I am not very familiar with Nuxt.js, so could you please provide a quick and dirty scaffolding to try a demo application using the same setup of your repo? Otherwise I am possibly following a totally unrelated path here.

Also, in order to remove one of the possible culprits (i.e.: Vercel deployment), could you please check if your application built and started locally has the same issue of the production one? I mean you could launch the application locally and browse it from your local address using a mobile device.

Thanks!

**Comment by florian-lefebvre** [comment]
I will provide a sample repo instead a small snippet and I'll also try to execute my app on my phone

**Comment by P3trur0** [comment]
hello @florian-lefebvre, I was able to reproduce the problem since another user mentioned that.

Here I come with a possible workaround:

https://github.com/P3trur0/vue-country-flag/issues/69#issuecomment-854613745

In your case I'd advocate for the adoption of the first alternative. Please, let me know if this solves your issue.

**Comment by florian-lefebvre** [comment]
Hi @P3trur0, thanks I'll try that and keep you informed.

**Comment by radimhornicek** [comment]
Maybe it will help someone: for me the problem was that I applied a css class to the flag component, where I had a 1px border set on...
