### ISSUE TITLE
adblock block andorra flag

### ISSUE THREAD

**Issue by AdrianLech** [P3trur0/vue-country-flag#27]
adblock (from https://getadblock.com/) blocks the andorra flag cause the class is f-ad. could you please change the andorra flag class?

**Comment by P3trur0** [comment]
Hi @AdrianLech, thanks for pointing this out!
I'll fix it ASAP :smiley_cat:

**Comment by P3trur0** [comment]
@AdrianLech thanks for reporting the issue. It has been fixed with **v.2.0.1**.
