### ISSUE TITLE
.f isn't scoped to the componet

### ISSUE THREAD

**Issue by VizualAbstract** [P3trur0/vue-country-flag#28]
Any element with the class of .f is being styled by the styles in this component.

In our application, our customers are allowed to create or provide supplemental HTML, and some customers use `'f'` as a class. This is causing many of their UIR elements to appear broken.

**Comment by P3trur0** [comment]
Hi @VizualAbstract, thanks for pointing out the issue. Would '.flag' be ok instead?

**Comment by VizualAbstract** [comment]
I think so! @P3trur0

I know for my team, I always recommend we prefix our classes. Our company's initicals are rc, so I use `.rc_`, but that's just our preference. Either way, .flag would be a great upgrade

**Comment by P3trur0** [comment]
Cool! I think I'll some spare time to work on it tomorrow. Otherwise, if you are in a rush, please consider to do it by yourself and open a PR :)

**Comment by P3trur0** [comment]
Hi @VizualAbstract, please check out version 2.0.1. As suggested, the main CSS class of the component has been renamed to `flag`. Hope it helps to solve your issue.
