### ISSUE TITLE
Nuxt: Sizes not working

### ISSUE THREAD

**Issue by rubennaatje** [P3trur0/vue-country-flag#32]
Hi, 
I can't get the sizes to work in Nuxt. I think I might be missing something?

@plugins/vue-flags.js
```js
import Vue from 'vue';
import CountryFlag from 'vue-country-flag';

Vue.use(CountryFlag);
```
in my nuxt.config
```js
  plugins: [
    { src: '@/plugins/vue-flags.js' }
]
```
and in a component I want to use it in,
```html
 <CountryFlag country="fr" size="small" />
```

Yet the size attribute doesn't do anything, it's always normal size which is too big for my use case. 

I might be missing a step or it just doesn't work with Nuxt?

**Comment by P3trur0** [comment]
Hi @rubennaatje, thanks for pointing this out. Indeed your configuration seems ok. I will investigate. Just for proper troubleshooting, did you try also with older versions of vue-country-flag? I mean this one:

https://www.npmjs.com/package/vue-country-flag/v/1.3.1

**Comment by apiret** [comment]
Hi,

Just for information, I just tried to use vue-country-flag 2.0.1 with nuxt 2.12.2 and I have no problem with the size.

@plugins/vue-flags.ts
```javascript
import Vue from "vue";
import CountryFlag from "vue-country-flag";
Vue.use(CountryFlag);
```

in my nuxt.config
```javascript
plugins: [
     "~/plugins/vue-flags"
  ]
```

and in my page
```html
<countryFlag country="fr" size="small"/>
<countryFlag country="it" />
<countryFlag country="de" size="big"/>
<countryFlag country="es" size="normal"/>
```

![Screenshot 2020-05-24 at 15 53 53](https://user-images.githubusercontent.com/1142871/82755873-d62c2180-9dd6-11ea-863d-6afe80a46acb.png)

**Comment by P3trur0** [comment]
Hi @apiret thanks for sharing your experience here! @rubennaatje please try to check if is there any difference with your setup, in order to help me in better investigating on this.

**Comment by rubennaatje** [comment]
My bad I've been very busy, so i'll check again. code does seem to be the same as apiret though.

Difference might be that I run it in an electron app. But i'll test again asap.

**Comment by yiyasha15** [comment]
im not able to pass object.data in the country field..

**Comment by P3trur0** [comment]
hi @yiyasha15, do you have a concrete example?

**Comment by P3trur0** [comment]
see #58.
