### ISSUE TITLE
I have country name from an API, how can I bind it to country attribute? 

### ISSUE THREAD

**Issue by yiyasha15** [P3trur0/vue-country-flag#36]

**Comment by yiyasha15** [comment]
I created a data method which returns value of the country, 
```
data() {
      return {
        flag: this.artist.country
      }
    }
```
In my template I have
`<country-flag country= flag />`


But the flag image is not showing.

**Comment by P3trur0** [comment]
Hi @yiyasha15,

I'd expect you pass the reactive attribute like this:

`<country-flag :country="country.flag"/>`

where `country.flag` is the dynamic value received from an API. You can see an example in action [here](https://github.com/P3trur0/vue-country-flag/blob/gh-pages/index.html#L98).
This renders the [following output](https://flatmap.it/vue-country-flag/).  

Let me know if this solves your issue 😺

**Comment by yiyasha15** [comment]
Hi @P3trur0 ,
Thanks alot it worked! 😺
