### ISSUE TITLE
ISO 3166 alpha-3 support

### ISSUE THREAD

**Issue by hdpinto** [P3trur0/vue-country-flag#4]
Any plans to include ISO 3166 alpha-3 support? Is this something that you'd accept a PR for?

**Comment by P3trur0** [comment]
Hi @hdpinto, sure, it'd be beneficial for the component, so please go ahead with it if you will :smile:

**Comment by P3trur0** [comment]
As suggested, the component now offers also alpha-3 support.
See PR #5
