### ISSUE TITLE
USSR flag request ☭

### ISSUE THREAD

**Issue by Qeenon** [P3trur0/vue-country-flag#40]
Hello.

Before USSR destruction people of USSR voted to save USSR, but leaders of UA Kravchuk, BLR Shuskevich and Russia Eltsin dissolved USSR in 1991.

Current Russian flag has controversial associations for many people, specially since WW2.
It is highly important for dozens of Russians to use USSR flag.

https://en.wikipedia.org/wiki/Flag_of_the_Soviet_Union

Thank you for understanding.

**Comment by P3trur0** [comment]
Hi, thanks for mentioning this. I will evaluate the introduction of this flag as well. Do you have idea of the letters to identify the flag (e.g.: `su`)?

**Comment by Qeenon** [comment]
@P3trur0 maybe `ussr` if that's not too long for identify

**Comment by Qeenon** [comment]
@P3trur0 also: https://www.iso.org/obp/ui/#iso:code:3166:SU

**Comment by P3trur0** [comment]
Yes, I'll go with `su` and `sun` since in the page you're linking above they are the official ISO alpha2 and alpha3 codes.

**Comment by P3trur0** [comment]
https://www.npmjs.com/package/vue-country-flag/v/2.0.3 solves it. 
Thanks for reporting the issue.

**Comment by Qeenon** [comment]
Thank you
