### ISSUE TITLE
This dependency was not found (vue3 + vue-country-flag-next)

### ISSUE THREAD

**Issue by picks44** [P3trur0/vue-country-flag#48]
Hello,

I've added the dependency **vue-country-flag-next** using **yarn** in my project, and followed the doc to register the component, but I get the following error
```
 ERROR  Failed to compile with 1 error                                                                                                                                                                             11:38:05
This dependency was not found:

* vue-country-flag in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/LocaleSwitcher.vue?vue&type=script&lang=js

To install it, you can run: npm install --save vue-country-flag
```
Here is how I registered it
```
<template>
 <country-flag :country="locale" size="big"/></option>
</template>

<script>
import CountryFlag from 'vue-country-flag'

export default {
  components: {
    CountryFlag
  }
}
</script>
```

**Comment by P3trur0** [comment]
Hi @picks44,

did you add the component, right?

I mean:

`yard add vue-country-flag-next`

**Comment by picks44** [comment]
Yes I did...

**Comment by kiwina** [comment]
Can confirm for some reason the ide doesn't find the package

**Comment by P3trur0** [comment]
Thanks for spotting this!

I am investigating how to fix the issue. Meanwhile you can use the following workaround:

```javascript
import CountryFlag from 'vue-country-flag-next/dist/CountryFlag.esm.js'
```

should temporarily fix the problem.

**Comment by P3trur0** [comment]
Please update to the latest 2.0.4 version that fixes the issue.
Thanks for trying this component on Vue3 😄 
@picks44 @kiwina

**Comment by BeneRichi** [comment]
dependency is stil not found when i install it with yarn.

import CountryFlag from 'vue-country-flag'

great work anyway. Thank you so much for that.

**Comment by P3trur0** [comment]
Hello @BeneRichi, thanks! Are you using vue2 or vue3 version?

**Comment by BeneRichi** [comment]
Vue 3

Von meinem iPhone gesendet

**Comment by P3trur0** [comment]
For Vue3 it'd be:

```javascript
import CountryFlag from 'vue-country-flag-next'
```

did you try it as well?

**Comment by BeneRichi** [comment]
Yes sure. It’s in your documentation :) I tried that.

He is also not finding the image source flag.png


Von meinem iPhone gesendet

**Comment by P3trur0** [comment]
Are you using SSR?

**Comment by BeneRichi** [comment]
Im using it but it’s deactivated at the moment.

So should not be a problem.

Von meinem iPhone gesendet

**Comment by P3trur0** [comment]
Mmm... I think there are some issues with SSR and those are still open. I hope to fix them in the near future. Alas, at the moment I have not enough spare time to provide a prompt workaround for your issue.
However, probably this could help:

https://github.com/P3trur0/vue-country-flag/issues/69#issuecomment-854613745

**Comment by BeneRichi** [comment]
Thx :)

No problem. I will try again when there is a new version.

But no stress..

Thanks 🙏 

Von meinem iPhone gesendet
