### ISSUE TITLE
Invalid or unexpected token

### ISSUE THREAD

**Issue by florian-lefebvre** [P3trur0/vue-country-flag#57]
"vue-country-flag": "^2.1.0"
"nuxt": "^2.15.4"

I get an error: `Invalid or unexpected token`. It was working with `^2.0.4`. The error occurs because of the SSR.

**Comment by P3trur0** [comment]
Do you have any snippet to share in order to reproduce the issue?

**Comment by P3trur0** [comment]
@florian-lefebvre thanks for spotting this. Latest v2.1.1 solves the problem.

**Comment by florian-lefebvre** [comment]
It works now, thanks !
