### ISSUE TITLE
background-image: url("[object Module]");

### ISSUE THREAD

**Issue by nekooee** [P3trur0/vue-country-flag#64]
Hi
flag image not loaded and show this code in HTML:
background-image: url("[object Module]");

please help me

![image](https://user-images.githubusercontent.com/6003803/119210620-72f4ce00-bac2-11eb-9d0a-181c7b324172.png)

I use laravel 8 and vue 2.5.17

**Comment by P3trur0** [comment]
Hello, could you please provide a snippet of your component?

**Comment by nekooee** [comment]
> Hello, could you please provide a snippet of your component?

thank you
The same code in my system displays the flag correctly. But after upload on the server, it displays an error!
main.js:
```javascript
import Vue from 'vue';
import CountryFlag from 'vue-country-flag'
Vue.component('country-flag', CountryFlag)

const app = new Vue({
    el: '#app',
    data: () => ({}),
   
});
```
myPage.blade.php
```php
 <div class="rounded-lg overflow-hidden flex items-center justify-center">
                        <country-flag :country="'{{$CurrentLanguage["Country"]}}'" size='normal'></country-flag>
 </div>
```

**Comment by nekooee** [comment]
@P3trur0 Did you see my message?

**Comment by P3trur0** [comment]
Hello @nekooee, sorry, but so far I had no time to investigate the issue. Probably I'll do that in the next days.
Meanwhile, as possible workaround, you could install previous 2.0.4 version, where the usage of the background was different from the current one.

Please, install the component like this:

`npm install vue-country-flag@2.0.4`

Besides the above mentioned different backround usage, the component of this older version is basically the same.

**Comment by P3trur0** [comment]
Hello @nekooee, it may be because of the following: https://github.com/vuejs/vue-loader/issues/1612

Do you have any chance to do a check with latest **vue-country-flag** version and the solution discussed in the mentioned issue, please?

Alternatively, as I mentioned in my comment above, you'd be fine with `npm install vue-country-flag@2.0.4` as well.

**Comment by nekooee** [comment]
> Hello @nekooee, it may be because of the following: [vuejs/vue-loader#1612](https://github.com/vuejs/vue-loader/issues/1612)
> 
> Do you have any chance to do a check with latest **vue-country-flag** version and the solution discussed in the mentioned issue, please?
> 
> Alternatively, as I mentioned in my comment above, you'd be fine with `npm install vue-country-flag@2.0.4` as well.

thank you. I tested and vue-country-flag@2.0.4 Works well.
I have already seen the link you introduced. It says disable esModule. But this may cause problems for my other code. 
On the other hand, I use the Laravel mix in which the webpack settings are slightly different. And I do not know exactly how to disable the esModule.

**Comment by P3trur0** [comment]
@nekooee thanks for reporting this!

**Comment by SidneySaints** [comment]
@P3trur0 this issue also exists in vue-country-flag-next used together with laravel-mix

**Comment by lephro** [comment]
Issue still exists. Latest versions are quite unuseable without a fix. Would be cool if this issue could be fixed at some point.

**Comment by nekooee** [comment]
> Issue still exists. Latest versions are quite unuseable without a fix. Would be cool if this issue could be fixed at some point.

Unfortunately, because the size of the maps has changed in the last version and it has extra margins and in addition, they are square instead of rectangular, I think it is better to use the old version as before. 
The only drawback in the old version, which is also present in the new version, is the map format instead of webp or other new formats in png format, which I had to edit myself.

**Comment by P3trur0** [comment]
Thanks for reporting this. Eventually I picked the decision to restore the same behavior of older 2.0.4, namely by embedding the flags sprite in a Base64 encoded url.  

Latest 2.3.1 restores the behavior.

Please, if you have any idea to make this component better I am definitely open to discussion 😄
