### ISSUE TITLE
Flags have incorrect size on IE & Edge browser

### ISSUE THREAD

**Issue by hudy1** [P3trur0/vue-country-flag#7]
Hi,

there is something wrong with displaying flags on IE/Edge. They don't have inline style for transform scale, so provided size doesn't apply. On Chrome, Firefox & Opera problem doesn't exist.

Only workaround I found to set inline style manually.

**Comment by P3trur0** [comment]
Hi @hudy1, thanks for pointing that out! I'll give it a look tonight 😺

**Comment by P3trur0** [comment]
@hudy1 the problem is fixed with **v1.1.1**. Please give it a try!

**Comment by hudy1** [comment]
It works, thanks :)
