### ISSUE TITLE
Support typscript in vue-country-flag-next

### ISSUE THREAD

**Issue by micm0** [P3trur0/vue-country-flag#72]
I'm using the next library in a Vue 3 project with Typescript. When I import the library with `import CountryFlag from 'vue-country-flag-next';`  I get this error `Cannot find module 'vue-country-flag-next' or its corresponding type declarations.`

I created a new file  `vue-country-flag-next.d.ts`  in my project with `declare module 'vue-country-flag-next';` as a workaround but It could be nice to support typing :D

**Comment by itapingu** [comment]
When you think this will be added? Causing some pain when testing stuff that require your component inside jest :) will be really appreciate if you add the declaration.
