### ISSUE TITLE
Rounded property no longer works in latest version (v.2.1.1)

### ISSUE THREAD

**Issue by alfienguyen** [P3trur0/vue-country-flag#74]
Might be related to the fix for #26 Now the rounded property seems to have no effect.

**Comment by P3trur0** [comment]
Thanks for opening this, I'll take a look!

**Comment by P3trur0** [comment]
2.3.1 fixes the issue.

**Comment by Sjoerd82** [comment]
"rounded" not working in v2.3.2 of **vue-country-flag-next**
