### ISSUE TITLE
Add CSP support

### ISSUE THREAD

**Issue by ricardo17coelho** [P3trur0/vue-country-flag#79]
Remove inline styles (styleInject) to support CSP (Content Security Policy).

Error:
![image](https://user-images.githubusercontent.com/37732431/129035651-62fef2cc-a553-4f2e-bfbe-c0dd3d7acd5a.png)

**Comment by P3trur0** [comment]
Hi @ricardo17coelho, thanks for reporting this! It's in my spare time backlog :)

**Comment by P3trur0** [comment]
This should be resolved by latest 2.3.1. Thanks for reporting the issue!
