### ISSUE TITLE
Suport for contry code Ex: cr = 506

### ISSUE THREAD

**Issue by SergioAraya** [P3trur0/vue-country-flag#83]

**Comment by P3trur0** [comment]
thanks @SergioAraya is CR Costa Rica, right?
Thanks for opening this! 🇨🇷

**Comment by SergioAraya** [comment]
yes, it is

**Comment by P3trur0** [comment]
Thanks. Actually I see that flag-cr is already supported by the component. Do you have any problem in rendering? I'd expect `flag-cr` or `flag-cri`.

**Comment by SergioAraya** [comment]
a problem, not. The thing is that I have a database with many countries
that does not have the alpha_2 and alpha_3, just the country code: 1 ,2,
506... and so on, but I did a management view to solve the problem.

**Comment by SergioAraya** [comment]
The issue could be closed. And advice could be add support for country code
like 506, 550, 1... if possible.

thanks.
