### ISSUE TITLE
get rid of hidden margin?

### ISSUE THREAD

**Issue by petegriffith** [P3trur0/vue-country-flag#92]
Right now the sprites seem to have some sort of hidden margin, possibly described in issue #14 

I would like the flag sprite to have no margin at all, and to be exactly as big as the sprite itself, so that I can avoid issues like this:

![image](https://user-images.githubusercontent.com/72716356/142959655-d2e45bc0-9606-412e-9f59-09d4dd9fdd95.png)

Where there is a huge hidden margin (padding?) that won't allow the flag to align with the flexbox's `aligh-items: flex-end` prop:

![image](https://user-images.githubusercontent.com/72716356/142959748-c84ad4d1-bf3a-4b94-b9b2-736d8204e07e.png)

The height of the `<span>` that the package renders is fine I think

![image](https://user-images.githubusercontent.com/72716356/142959805-501cb1cf-5703-4a06-a317-e0284e465680.png)

But the browser tools show a different height/width without margin or padding:

![image](https://user-images.githubusercontent.com/72716356/142959840-66655d2a-c67c-45e8-a33c-688b8b14c38d.png)

For reference, here's the element in the console:

![image](https://user-images.githubusercontent.com/72716356/142959903-d68211cb-0593-4e61-a988-59e43f2f8009.png)

**Comment by P3trur0** [comment]
Thanks for opening this! Probably in my last commit I unadvertedly pushed something wrong.
I'll investigate today :wink:

**Comment by P3trur0** [comment]
@petegriffith after some investigation I came with a solution that you can find in version 2.3.2.
