### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c')

### ISSUE THREAD

**Issue by DimLeon** [P3trur0/vue-country-flag#97]
I installed latest version (2.3.2).
My vue js version is 3.2.26.

Following the docs, after importing & registering in specific component, I use e.g. the following:
`<country-flag country='fr' size='small'/>`   
The error I get is 
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.__vue_render__ (country-flag.esm.js?eea2:231:1) etc..
```
I get the error from line 231 in country-flag.esm.js
Any ideas?

**Comment by DimLeon** [comment]
For some reason the error gone after removing and reinstalling the package as dev dependency. 
Doesn't really make sense. Anyway, it is working great now

**Comment by Pfahlf** [comment]
Just for information, I have the same error.
